package rehlat.model;

import rehlat.interfaces.Reportable;
import java.util.ArrayList;


public class Administrator extends User implements Reportable {

    private int accessLevel;

    public Administrator(int userId, String fullName, String email,
                         String password, String phone, int accessLevel) {
        super(userId, fullName, email, password, phone);
        this.accessLevel = accessLevel;
    }


    public int getAccessLevel() {
        return accessLevel;
    }

    public void setAccessLevel(int accessLevel) {
        this.accessLevel = accessLevel;
    }


    @Override
    public String getRole() {
        return "Administrator";
    }


    @Override
    public void showDashboard() {
        System.out.println("=== Administrator Dashboard ===");
        System.out.println("Welcome, " + getFullName());
        System.out.println("Access Level: " + accessLevel);
    }

    @Override
    public String generateReport() {
        return "=== System Report ===\nGenerated by: " + getFullName()
                + "\nAccess Level: " + accessLevel;
    }


    public String generateUserReport(ArrayList<User> allUsers) {
        String report = "=== User Report ===\n";
        report = report + "Total Users: " + allUsers.size() + "\n\n";
        for (int i = 0; i < allUsers.size(); i++) {
            report = report + allUsers.get(i).toString() + "\n";
        }
        return report;
    }

    @Override
    public String toString() {
        return super.toString() + " | Access Level: " + accessLevel;
    }
}
