package rehlat.gui;

import rehlat.db.UserRepository;
import rehlat.model.Administrator;
import rehlat.model.User;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class ReportForm extends JFrame {

    public ReportForm(Administrator admin) {
        setTitle("System Report");
        setSize(520, 450);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        buildForm(admin);
        setVisible(true);
    }

    private void buildForm(Administrator admin) {
        setLayout(new BorderLayout());

        add(UITheme.createHeader("System Report", "Generated by: " + admin.getFullName()), BorderLayout.NORTH);

        ArrayList<User> allUsers = UserRepository.getAllUsers();
        String reportText = admin.generateUserReport(allUsers);

        JTextArea textArea = new JTextArea(reportText);
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 13));
        textArea.setBackground(UITheme.GRAY_LIGHT);
        textArea.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 10));
        bottomPanel.setBackground(UITheme.GRAY_LIGHT);
        JButton closeBtn = UITheme.createOutlineButton("Close");
        closeBtn.addActionListener(e -> dispose());
        bottomPanel.add(closeBtn);

        add(new JScrollPane(textArea), BorderLayout.CENTER);
        add(bottomPanel, BorderLayout.SOUTH);
    }
}
